---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

images:
  - name: quay.io/enterprise-contract-samples/hello-world:latest
    digest: sha256:e7ec7239af437e31884bc5220974d072f1fa3e86413503a7cdee660a0d76a9d6

