---
name: Checks

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  check-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install ec-cli
      run: |-
        mkdir -p "${HOME}/.local/bin"
        curl -sL https://github.com/enterprise-contract/ec-cli/releases/download/snapshot/ec_linux_amd64 -o "${HOME}/.local/bin/ec"
        chmod +x "${HOME}/.local/bin/ec"
        ec version

    - name: verify production images
      run: ./hack/validate-images.sh prod
